rails_app/config/routes.rb
PowerStorm::Application.routes.draw do


  get "contact/index"

  get "about" => "about_page#index"
  get "contact" => "contact#index"
 
  match "about" => "about_page#index"
  match "contact" => "contact#index"
  match "admin" => "Admin#index"
  
  resources :buildings
  resources :users
  resources :weathers
  resources :electricity_readings
  resources :meters
  
  root :to => 'Buildings#index'
  
  match 'abr/:abbreviation' => 'Buildings#show'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :buildings do
    post 'ajax_update' => :ajax_update
  end
  
  controller :buildings do
	get 'change_view_mode/:view_mode' => :change_view_mode
  end
end

rails_app/app/models/electricity_reading.rb
class ElectricityReading < ActiveRecord::Base
  belongs_to :meter
  # TODO build up dependencies & stoff
end

rails_app/app/controllers/electricity_readings_controller.rb
class ElectricityReadingsController < ApplicationController
  # GET /electricity_readings
  # GET /electricity_readings.xml
  def index
    @electricity_readings = ElectricityReading.all.reverse #.paginate(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @electricity_readings }
    end
  end

  # GET /electricity_readings/1
  # GET /electricity_readings/1.xml
  def show
    @electricity_reading = ElectricityReading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @electricity_reading }
    end
  end

  # GET /electricity_readings/new
  # GET /electricity_readings/new.xml
  def new
    @electricity_reading = ElectricityReading.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @electricity_reading }
    end
  end

  # GET /electricity_readings/1/edit
  def edit
    @electricity_reading = ElectricityReading.find(params[:id])
  end

  # POST /electricity_readings
  # POST /electricity_readings.xml
  def create
    @electricity_reading = ElectricityReading.new(params[:electricity_reading])

    respond_to do |format|
      if @electricity_reading.save
        format.html { redirect_to(@electricity_reading, :notice => 'Electricity reading was successfully created.') }
        format.xml  { render :xml => @electricity_reading, :status => :created, :location => @electricity_reading }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @electricity_reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /electricity_readings/1
  # PUT /electricity_readings/1.xml
  def update
    @electricity_reading = ElectricityReading.find(params[:id])

    respond_to do |format|
      if @electricity_reading.update_attributes(params[:electricity_reading])
        format.html { redirect_to(@electricity_reading, :notice => 'Electricity reading was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @electricity_reading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /electricity_readings/1
  # DELETE /electricity_readings/1.xml
  def destroy
    @electricity_reading = ElectricityReading.find(params[:id])
    @electricity_reading.destroy

    respond_to do |format|
      format.html { redirect_to(electricity_readings_url) }
      format.xml  { head :ok }
    end
  end
end

rails_app/app/helpers/electricity_readings_helper.rb
module ElectricityReadingsHelper
end

rails_app/app/views/electricity_readings/_form.html.erb
<%= form_for(@electricity_reading) do |f| %>
  <% if @electricity_reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@electricity_reading.errors.count, "error") %> prohibited this electricity_reading from being saved:</h2>

      <ul>
      <% @electricity_reading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_time %><br />
    <%= f.datetime_select :date_time %>
  </div>
  <div class="field">
    <%= f.label :meter_id %><br />
    <%= f.text_field :meter_id %>
  </div>
  <div class="field">
    <%= f.label :power %><br />
    <%= f.text_field :power %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/electricity_readings/edit.html.erb
<h1>Editing electricity_reading</h1>

<%= render 'form' %>

<%= link_to 'Show', @electricity_reading %> |
<%= link_to 'Back', electricity_readings_path %>

rails_app/app/views/electricity_readings/index.html.erb
<h1>Listing electricity_readings</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Date time</th>
    <th>Meter</th>
    <th>Power</th>
  </tr>
  
<% @electricity_readings.each do |electricity_reading| %>
  <tr>
    <td><%= electricity_reading.id %></td>
    <td><%= electricity_reading.date_time %></td>
    <td><%= electricity_reading.meter_id %></td>
    <td><%= electricity_reading.power %></td>
    <td><%= link_to 'Show', electricity_reading %></td>
    <td><%= link_to 'Edit', edit_electricity_reading_path(electricity_reading) %></td>
    <td><%= link_to 'Destroy', electricity_reading, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Electricity reading', new_electricity_reading_path %>

rails_app/app/views/electricity_readings/new.html.erb
<h1>New electricity_reading</h1>

<%= render 'form' %>

<%= link_to 'Back', electricity_readings_path %>

rails_app/app/views/electricity_readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date time:</b>
  <%= @electricity_reading.date_time %>
</p>

<p>
  <b>Meter:</b>
  <%= @electricity_reading.meter_id %>
</p>

<p>
  <b>Power:</b>
  <%= @electricity_reading.power %>
</p>


<%= link_to 'Edit', edit_electricity_reading_path(@electricity_reading) %> |
<%= link_to 'Back', electricity_readings_path %>