rails_app/config/routes.rb
PowerStorm::Application.routes.draw do


  get "contact/index"

  get "about" => "about_page#index"
  get "contact" => "contact#index"
 
  match "about" => "about_page#index"
  match "contact" => "contact#index"
  match "admin" => "Admin#index"
  
  resources :buildings
  resources :users
  resources :weathers
  resources :electricity_readings
  resources :meters
  
  root :to => 'Buildings#index'
  
  match 'abr/:abbreviation' => 'Buildings#show'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :buildings do
    post 'ajax_update' => :ajax_update
  end
  
  controller :buildings do
	get 'change_view_mode/:view_mode' => :change_view_mode
  end
end

rails_app/app/models/weather.rb
class Weather < ActiveRecord::Base
end

rails_app/app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  # GET /weathers
  # GET /weathers.xml
  def index
    @weathers = Weather.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @weathers }
    end
  end

  # GET /weathers/1
  # GET /weathers/1.xml
  def show
    @weather = Weather.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @weather }
    end
  end

  # GET /weathers/new
  # GET /weathers/new.xml
  def new
    @weather = Weather.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @weather }
    end
  end

  # GET /weathers/1/edit
  def edit
    @weather = Weather.find(params[:id])
  end

  # POST /weathers
  # POST /weathers.xml
  def create
    @weather = Weather.new(params[:weather])

    respond_to do |format|
      if @weather.save
        format.html { redirect_to(@weather, :notice => 'Weather was successfully created.') }
        format.xml  { render :xml => @weather, :status => :created, :location => @weather }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @weather.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /weathers/1
  # PUT /weathers/1.xml
  def update
    @weather = Weather.find(params[:id])

    respond_to do |format|
      if @weather.update_attributes(params[:weather])
        format.html { redirect_to(@weather, :notice => 'Weather was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @weather.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.xml
  def destroy
    @weather = Weather.find(params[:id])
    @weather.destroy

    respond_to do |format|
      format.html { redirect_to(weathers_url) }
      format.xml  { head :ok }
    end
  end
end

rails_app/app/helpers/weathers_helper.rb
module WeathersHelper
end

rails_app/app/views/weathers/_form.html.erb
<%= form_for(@weather) do |f| %>
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% @weather.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :today %><br />
    <%= f.datetime_select :today %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br />
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/weathers/edit.html.erb
<h1>Editing weather</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

rails_app/app/views/weathers/index.html.erb
<h1>Listing weathers</h1>

<table>
  <tr>
    <th>Today</th>
    <th>Temperature</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weathers.each do |weather| %>
  <tr>
    <td><%= weather.today %></td>
    <td><%= weather.temperature %></td>
    <td><%= weather.description %></td>
    <td><%= link_to 'Show', weather %></td>
    <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
    <td><%= link_to 'Destroy', weather, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weather', new_weather_path %>

rails_app/app/views/weathers/new.html.erb
<h1>New weather</h1>

<%= render 'form' %>

<%= link_to 'Back', weathers_path %>

rails_app/app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Today:</b>
  <%= @weather.today %>
</p>

<p>
  <b>Temperature:</b>
  <%= @weather.temperature %>
</p>

<p>
  <b>Description:</b>
  <%= @weather.description %>
</p>


<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>