rails_app/config/routes.rb
PowerStorm::Application.routes.draw do


  get "contact/index"

  get "about" => "about_page#index"
  get "contact" => "contact#index"
 
  match "about" => "about_page#index"
  match "contact" => "contact#index"
  match "admin" => "Admin#index"
  
  resources :buildings
  resources :users
  resources :weathers
  resources :electricity_readings
  resources :meters
  
  root :to => 'Buildings#index'
  
  match 'abr/:abbreviation' => 'Buildings#show'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  controller :buildings do
    post 'ajax_update' => :ajax_update
  end
  
  controller :buildings do
	get 'change_view_mode/:view_mode' => :change_view_mode
  end
end

rails_app/app/models/meter.rb
class Meter < ActiveRecord::Base
  belongs_to :building
  has_many :electricity_readings
end

rails_app/app/controllers/meters_controller.rb
class MetersController < ApplicationController
  # GET /meters
  # GET /meters.xml
  def index
    @meters = Meter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @meters }
    end
  end

  # GET /meters/1
  # GET /meters/1.xml
  def show
    @meter = Meter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meter }
    end
  end

  # GET /meters/new
  # GET /meters/new.xml
  def new
    @meter = Meter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meter }
    end
  end

  # GET /meters/1/edit
  def edit
    @meter = Meter.find(params[:id])
  end

  # POST /meters
  # POST /meters.xml
  def create
    @meter = Meter.new(params[:meter])

    respond_to do |format|
      if @meter.save
        format.html { redirect_to(@meter, :notice => 'Meter was successfully created.') }
        format.xml  { render :xml => @meter, :status => :created, :location => @meter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meters/1
  # PUT /meters/1.xml
  def update
    @meter = Meter.find(params[:id])

    respond_to do |format|
      if @meter.update_attributes(params[:meter])
        format.html { redirect_to(@meter, :notice => 'Meter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meters/1
  # DELETE /meters/1.xml
  def destroy
    @meter = Meter.find(params[:id])
    @meter.destroy

    respond_to do |format|
      format.html { redirect_to(meters_url) }
      format.xml  { head :ok }
    end
  end
end

rails_app/app/helpers/meters_helper.rb
module MetersHelper
end

rails_app/app/views/meters/_form.html.erb
<%= form_for(@meter) do |f| %>
  <% if @meter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meter.errors.count, "error") %> prohibited this meter from being saved:</h2>

      <ul>
      <% @meter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br />
    <%= f.text_field :building_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/meters/edit.html.erb
<h1>Editing meter</h1>

<%= render 'form' %>

<%= link_to 'Show', @meter %> |
<%= link_to 'Back', meters_path %>

rails_app/app/views/meters/index.html.erb
<h1>Listing meters</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Ip</th>
    <th>Building</th>
  </tr>

<% @meters.each do |meter| %>
  <tr>
    <td><%= meter.id %></td>
    <td><%= meter.ip %></td>
    <td><%= meter.building_id %></td>
    <td><%= link_to 'Show', meter %></td>
    <td><%= link_to 'Edit', edit_meter_path(meter) %></td>
    <td><%= link_to 'Destroy', meter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meter', new_meter_path %>

rails_app/app/views/meters/new.html.erb
<h1>New meter</h1>

<%= render 'form' %>

<%= link_to 'Back', meters_path %>

rails_app/app/views/meters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip:</b>
  <%= @meter.ip %>
</p>

<p>
  <b>Building:</b>
  <%= @meter.building_id %>
</p>


<%= link_to 'Edit', edit_meter_path(@meter) %> |
<%= link_to 'Back', meters_path %>